### PR TITLE
Replace Travis CI with GitHub actions

### PR DESCRIPTION
**Pull request by m-ober**
This PR replaces Travis CI with GitHub actions.

When a tag with name `v(.*)` is pushed, a release archive is built and a draft release on GitHub is created.

### CODE REVIEW

**Comment by m-ober** [comment]
This may be a matter of personal preference, but I like GitHub actions more for one reason: It keeps working if you fork a repository, no need to set up a(nother) external service.

**Comment by schinken** [comment]
Splendid! :)

**Comment by schinken** [comment]
Do I have to do something for the workflow to run? tried to publish a new version

**Comment by schinken** [comment]
lol. forgot to push the tag, but created it. Sorry :D

**Comment by schinken** [comment]
np np :) 
If we have this, a new release with your changes is ready :)

**Comment by m-ober** [comment]
Travis might be broken because of this line:

`wget https://github.com/strichliste/strichliste-backend/releases/download/v1.8.0/strichliste-backend.tar.gz`

This files does not exist, the correct one is:

https://github.com/strichliste/strichliste-backend/releases/download/v1.8.0/strichliste-backend-v1.8.0.tar.gz

Note the version in the filename. So maybe it's sufficient to update this filename here:

https://github.com/strichliste/strichliste/blob/master/.travis.yml#L3

Or change the filename of the asset here:

https://github.com/strichliste/strichliste-backend/blob/master/.github/workflows/package.yml#L67

(remove `-${{ steps.branch_name.outputs.SOURCE_TAG }}`)

**Comment by m-ober** [comment]
I see - I will look at porting it to GitHub Actions as soon as time permits.

**Comment by schinken** [comment]
no hurry, and thanks! :)

**Pull request merged**
